# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

# The model half of the Kostenstellen detail (fin/cost_centers/_detail): one
# formatter per field of a WsjrdpCostCenter that shows more than its stored
# value, found by the name rule of Fin::AttrFormatHelper
# (fin_format_wsjrdp_cost_center_<attr>).
#
# The labels of the fields live in
# de.activerecord.attributes.wsjrdp_cost_center; a field without a formatter
# takes the finance type rules of Fin::AttrFormatHelper -- which is why the
# number, the two names and the two texts need none.
#
# The budgets are signed decimals in the base currency (expenses negative, the
# sign convention of datev_bookings.amount) and are shown in the money format of
# the Finanzen lists. A decimal that is not named `*_amount` does not reach the
# money type rule, so each of them carries a formatter of its own.
module Fin::CostCentersHelper
  # The four yearly budgets, defined off the concern's own year range, so the
  # set of formatters cannot drift from WsjrdpBudgetable::BUDGET_YEARS. The
  # names are the ones the lookup asks for:
  # fin_format_wsjrdp_cost_center_budget_2025 ... _budget_2028.
  WsjrdpBudgetable::BUDGET_YEARS.each do |year|
    define_method(:"fin_format_wsjrdp_cost_center_budget_#{year}") do |cost_center|
      fin_money(cost_center.budget_for(year))
    end
  end

  # The Moss status in words, as every other finance view spells it.
  def fin_format_wsjrdp_cost_center_moss_status(cost_center)
    moss_status_cell(cost_center.moss_status)
  end

  # The person responsible for the cost center: a link to them, with the new-tab
  # companion icon of the finance rows. `manager_name` beside it is the name the
  # master data carries as text, whether or not it resolves to a person here.
  def fin_format_wsjrdp_cost_center_manager(cost_center)
    person = cost_center.manager
    person && assoc_link_with_newtab(person)
  end

  # The total budget somebody set by hand for the whole period.
  def fin_format_wsjrdp_cost_center_explicit_total_budget(cost_center)
    fin_money(cost_center.explicit_total_budget)
  end

  # The total the pages show. It is generated by the database, so the help line
  # says where the number comes from -- otherwise a total that matches neither
  # the yearly sum nor the explicit entry would read like an error.
  def fin_format_wsjrdp_cost_center_effective_total_budget(cost_center)
    {value: fin_money(cost_center.effective_total_budget),
     help: "Automatisch berechnet: die Summe der Jahresbudgets oder das explizit " \
           "gesetzte Gesamtbudget, je nachdem welcher Betrag absolut größer ist."}
  end
end
