# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

# The model half of the Kostenstellen detail (fin/cost_centers/_detail): one
# formatter per field of a WsjrdpCostCenter that shows more than its stored
# value, found by the name rule of Fin::AttrFormatHelper
# (fin_format_wsjrdp_cost_center_<attr>).
#
# The labels of the fields live in
# de.activerecord.attributes.wsjrdp_cost_center; a field without a formatter
# takes the finance type rules of Fin::AttrFormatHelper -- which is why the
# number, the two names and the two texts need none.
#
# The budgets are decimals in the base currency (expense budgets, stored
# positive -- WsjrdpBudgetable) and are shown in the money format of the
# Finanzen lists, sign included. A decimal that is not named `*_amount` does not
# reach the money type rule, so each of them carries a formatter of its own.
module Fin::CostCentersHelper
  # The four yearly budgets, defined off the concern's own year range, so the
  # set of formatters cannot drift from WsjrdpBudgetable::BUDGET_YEARS. The
  # names are the ones the lookup asks for:
  # fin_format_wsjrdp_cost_center_budget_2025 ... _budget_2028.
  WsjrdpBudgetable::BUDGET_YEARS.each do |year|
    define_method(:"fin_format_wsjrdp_cost_center_budget_#{year}") do |cost_center|
      fin_money(cost_center.budget_for(year))
    end
  end

  # The Moss status in words, as every other finance view spells it.
  def fin_format_wsjrdp_cost_center_moss_status(cost_center)
    moss_status_cell(cost_center.moss_status)
  end

  # The person responsible for the cost center: a link to them, with the new-tab
  # companion icon of the finance rows. `manager_name` beside it is the name the
  # master data carries as text, whether or not it resolves to a person here.
  def fin_format_wsjrdp_cost_center_manager(cost_center)
    person = cost_center.manager
    person && assoc_link_with_newtab(person)
  end

  # The total budget somebody set by hand for the whole period.
  def fin_format_wsjrdp_cost_center_explicit_total_budget(cost_center)
    fin_money(cost_center.explicit_total_budget)
  end

  # Whether this cost center is a unit's OWN -- ja / nein, the two words every
  # yes/no field of the Buchhaltung pages is written with. The flag is nullable
  # and defaults to false, so an unanswered cost center reads "nein".
  def fin_unit_cost_center_label(flag) = flag ? "ja" : "nein"

  def fin_format_wsjrdp_cost_center_is_unit_cost_center(cost_center)
    fin_unit_cost_center_label(cost_center.is_unit_cost_center)
  end

  # The Buchhaltung of the group a unit's own cost center belongs to (the group
  # whose cost_center_numbers name it), nil for any other cost center and for
  # one no group carries. The tables declare it as a double link beside
  # "Detailseite", the cost center's page puts it into its header.
  def fin_unit_group_bookkeeping_path(cost_center)
    return nil unless cost_center&.is_unit_cost_center

    group = fin_groups_by_cost_center_number[cost_center.number]
    group && group_finance_bookkeeping_path(group)
  end

  # The same as a double-link declaration (`t.detail_link`,
  # shared/wsjrdp/_detail_links): its url lambda takes a WsjrdpCostCenter or a
  # row that carries one (#cost_center).
  def fin_unit_group_bookkeeping_link
    {label: "Gruppen-Buchhaltung", icon: :book, title: "Buchhaltung der Gruppe öffnen",
     title_new_tab: "Buchhaltung der Gruppe in neuem Tab öffnen",
     url: ->(row) { fin_unit_group_bookkeeping_path(row.respond_to?(:cost_center) ? row.cost_center : row) }}
  end

  # {cost-center number => group}, ONE query per response for every row of a
  # table; a number two groups carry goes to the first by name.
  def fin_groups_by_cost_center_number
    # rubocop:disable Rails/HelperInstanceVariable -- per-response memo
    @fin_groups_by_cost_center_number ||= Group
      .where("groups.additional_info -> 'cost_center_numbers' IS NOT NULL")
      .where(deleted_at: nil).order(:name)
      .each_with_object({}) do |group, map|
        Array(group.cost_center_numbers).each { |number| map[number] ||= group }
      end
    # rubocop:enable Rails/HelperInstanceVariable
  end

  # The two choices of the flag's select on the detail. It is a plain yes/no,
  # so there is no third "nicht gesetzt": NULL and false mean the same thing.
  def fin_unit_cost_center_options = [["ja", "true"], ["nein", "false"]]

  # The total the pages show, generated by the database: the yearly sum or the
  # explicit total, whichever is larger in absolute value.
  def fin_format_wsjrdp_cost_center_effective_total_budget(cost_center)
    fin_money(cost_center.effective_total_budget)
  end
end
