# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

require "spec_helper"

# The fee columns of people, generated by the database:
#   wsjrdp_regular_full_fee  the fee of the payment role (the T&R tariff), or
#                            wsjrdp_regular_full_fee_override where set
#   wsjrdp_total_fee         wsjrdp_total_fee_override where set, else the
#                            regular full fee minus wsjrdp_total_fee_reduction
#                            and wsjrdp_extra_total_fee_reduction, not below 0
# The regular full fee is the tariff the payment plans are built from
# (WsjrdpInstallmentsHelper::PAYMENT_ROLE_TO_FULL_REGULAR_FEE_EUR); a missing
# or unknown role follows the scripts' rule. Ruby reads the columns
# (Person#total_fee_cents and friends) and sees a change right after the save.
describe Person, "fee columns" do
  let(:person) { people(:yp_a_1) }

  def fees_for(**columns)
    person.update_columns({payment_role: "RegularPayer::Group::Unit::Member", status: "confirmed",
                           wsjrdp_regular_full_fee_override: nil, wsjrdp_total_fee_reduction: 0,
                           wsjrdp_extra_total_fee_reduction: nil, wsjrdp_total_fee_override: nil}.merge(columns))
    person.reload
    [person.wsjrdp_regular_full_fee, person.wsjrdp_total_fee]
  end

  describe "wsjrdp_regular_full_fee" do
    it "is the fee of every known payment role, as Ruby computes it" do
      WsjrdpInstallmentsHelper::PAYMENT_ROLE_TO_FULL_REGULAR_FEE_EUR
        .select { |role, _| role.include?("::") }
        .each do |role, eur|
          regular, = fees_for(payment_role: role)
          expect(regular).to eq(eur), "#{role}: expected #{eur}, got #{regular}"
        end
    end

    it "is the same for single payment and installments" do
      expect(fees_for(payment_role: "EarlyPayer::Group::Unit::Member").first)
        .to eq(fees_for(payment_role: "RegularPayer::Group::Unit::Member").first).and eq(3400)
    end

    it "is 0 for an unknown role of a person without a contract or after a deregistration" do
      %w[registered deregistration_noted deregistered].each do |status|
        expect(fees_for(payment_role: "RegularPayer::", status: status).first).to eq(0)
        expect(fees_for(payment_role: nil, status: status).first).to eq(0)
      end
    end

    it "is an unmistakable placeholder for an unknown role otherwise" do
      expect(fees_for(payment_role: "RegularPayer::", status: "confirmed").first).to eq(10_000_000)
      expect(fees_for(payment_role: nil, status: "upload").first).to eq(10_000_000)
    end

    it "is the override where one is set, whatever the role" do
      expect(fees_for(wsjrdp_regular_full_fee_override: 1234.5).first).to eq(1234.5)
      expect(fees_for(payment_role: nil, status: "upload", wsjrdp_regular_full_fee_override: 0).first).to eq(0)
    end
  end

  describe "wsjrdp_total_fee" do
    it "is the regular full fee without reductions" do
      expect(fees_for).to eq([3400, 3400])
    end

    it "takes off both reductions, not below 0" do
      expect(fees_for(wsjrdp_total_fee_reduction: 1700).last).to eq(1700)
      expect(fees_for(wsjrdp_total_fee_reduction: 1700, wsjrdp_extra_total_fee_reduction: 312.5).last).to eq(1387.5)
      expect(fees_for(wsjrdp_extra_total_fee_reduction: 100).last).to eq(3300)
      expect(fees_for(wsjrdp_total_fee_reduction: 3000, wsjrdp_extra_total_fee_reduction: 1000).last).to eq(0)
    end

    it "starts from the overridden regular full fee" do
      expect(fees_for(wsjrdp_regular_full_fee_override: 1000, wsjrdp_total_fee_reduction: 250)).to eq([1000, 750])
    end

    it "is the total fee override where one is set, reductions and all" do
      expect(fees_for(wsjrdp_total_fee_override: 99.99, wsjrdp_total_fee_reduction: 1700).last).to eq(99.99)
      expect(fees_for(wsjrdp_total_fee_override: 0).last).to eq(0)
    end
  end

  describe "read by Ruby" do
    it "gives the fee methods the columns, in euros and in cents rounded half up" do
      fees_for(wsjrdp_total_fee_reduction: 12.345)

      expect(person.regular_full_fee_eur).to eq(3400)
      expect(person.regular_full_fee_cents).to eq(340_000)
      expect(person.total_fee_eur).to eq(BigDecimal("3387.655"))
      expect(person.total_fee_cents).to eq(338_766)
    end

    it "sees a change of an input right after the save, without a reload" do
      fees_for
      person.update!(wsjrdp_total_fee_reduction: 250)
      expect(person.total_fee_eur).to eq(3150)

      person.update!(payment_role: "RegularPayer::Group::Unit::Leader")
      expect(person.regular_full_fee_eur).to eq(2400)
      expect(person.total_fee_cents).to eq(215_000)
      expect(person).not_to have_changes_to_save
    end

    it "has no fee before the first save" do
      expect(Person.new.total_fee_cents).to be_nil
      expect(Person.new.regular_full_fee_eur).to be_nil
    end

    it "previews another reduction with the database's formula" do
      fees_for(wsjrdp_extra_total_fee_reduction: 100)
      preview = person.total_fee_eur_with_reduction(250)
      person.update!(wsjrdp_total_fee_reduction: 250)
      expect(person.total_fee_eur).to eq(preview).and eq(3050)
      expect(person.total_fee_cents_with_reduction(5000)).to eq(0)

      fees_for(wsjrdp_total_fee_override: 99.99)
      expect(person.total_fee_eur_with_reduction(250)).to eq(person.total_fee_eur).and eq(99.99)
    end
  end

  it "has read-only generated columns and writable plain ones" do
    expect(Person.columns_hash["wsjrdp_regular_full_fee"]).to be_virtual
    expect(Person.columns_hash["wsjrdp_total_fee"]).to be_virtual
    %w[wsjrdp_regular_full_fee_override wsjrdp_extra_total_fee_reduction wsjrdp_total_fee_override].each do |column|
      expect(Person.columns_hash[column]).not_to be_virtual
      expect(Person.columns_hash[column].null).to be(true)
      expect(Person.columns_hash[column].default).to be_nil
    end
    person.first_name = "Changed"
    expect { person.save! }.not_to raise_error
  end

  it "logs the overrides and the extra reduction, not the generated columns" do
    with_versioning do
      person.update!(wsjrdp_regular_full_fee_override: 1000, wsjrdp_extra_total_fee_reduction: 100,
        wsjrdp_total_fee_override: 850)
    end

    version = person.versions.reorder(:id).last
    expect(version.changeset.keys).to include("wsjrdp_regular_full_fee_override", "wsjrdp_extra_total_fee_reduction",
      "wsjrdp_total_fee_override")
    expect(version.object_changes).not_to include("wsjrdp_regular_full_fee:", "wsjrdp_total_fee:")
    expect(version.object.to_s).not_to include("wsjrdp_regular_full_fee:", "wsjrdp_total_fee:")
  end
end
