# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

require "spec_helper"

# The field formatters of the Kostenstellen detail.
#
# The records here are unsaved wherever they can be, and every value is
# invented -- names and budgets in this spec mean nothing.
describe Fin::CostCentersHelper do
  let(:ctx) { Fin::AttrFormatContext.regular }

  # Cost-center numbers may contain letters, which is why the fabricated one
  # does.
  def cost_center(**attrs) = WsjrdpCostCenter.new(number: "K900", **attrs)

  # The money format of the Finanzen lists joins number and symbol with a
  # non-breaking space.
  def money(text) = "#{text}#{Fin::MoneyHelper::NBSP}€"

  # The tinted status word of the summary lists (Fin::BookkeepingHelper
  # #moss_status_cell): the word says it, the class tints it.
  describe "the Moss status" do
    def status_span(**attrs)
      html = helper.fin_format_wsjrdp_cost_center_moss_status(cost_center(**attrs))
      Nokogiri::HTML.fragment(html).at_css("span.moss-status")
    end

    it "renders the tinted status word" do
      span = status_span(moss_status: "active")
      expect(span.text).to eq("aktiv")
      expect(span["class"].split).to contain_exactly("moss-status", "moss-status-active")
    end

    it "counts a cost center Moss does not know as inaktiv" do
      span = status_span
      expect(span.text).to eq("inaktiv")
      expect(span["class"].split).to contain_exactly("moss-status", "moss-status-inactive")
    end
  end

  describe "the responsible person" do
    it "hands the person to the finance association link" do
      person = Person.new(first_name: "Test", last_name: "Person")
      record = cost_center(manager: person)
      expect(helper).to receive(:assoc_link_with_newtab).with(person).and_return("LINK")

      expect(helper.fin_format_wsjrdp_cost_center_manager(record)).to eq("LINK")
    end

    it "is blank for a cost center without a manager" do
      expect(helper.fin_format_wsjrdp_cost_center_manager(cost_center)).to be_nil
    end
  end

  # One formatter per year, generated off WsjrdpBudgetable::BUDGET_YEARS -- so
  # the assertions walk that range instead of naming the four methods twice.
  describe "the yearly budgets" do
    def budget(year, **attrs)
      helper.send(:"fin_format_wsjrdp_cost_center_budget_#{year}", cost_center(**attrs))
    end

    it "answers for every budget year and for no other" do
      expect(WsjrdpBudgetable::BUDGET_YEARS.to_a).to eq([2025, 2026, 2027, 2028])
      WsjrdpBudgetable::BUDGET_YEARS.each do |year|
        expect(helper).to respond_to(:"fin_format_wsjrdp_cost_center_budget_#{year}")
      end
      expect(helper).not_to respond_to(:fin_format_wsjrdp_cost_center_budget_2029)
    end

    it "shows a budget in the money format of the Finanzen lists" do
      expect(budget(2025, budget_2025: 1500)).to eq(money("1.500,00"))
    end

    it "keeps the sign of a negative budget (an expense)" do
      expect(budget(2026, budget_2026: -2450.5)).to eq(money("-2.450,50"))
    end

    it "leaves a year without a budget blank" do
      WsjrdpBudgetable::BUDGET_YEARS.each do |year|
        expect(budget(year)).to be_nil
      end
    end
  end

  describe "the explicit total budget" do
    it "shows it in the money format" do
      expect(helper.fin_format_wsjrdp_cost_center_explicit_total_budget(
        cost_center(explicit_total_budget: -4000)
      )).to eq(money("-4.000,00"))
    end

    it "is blank when nobody set one" do
      expect(helper.fin_format_wsjrdp_cost_center_explicit_total_budget(cost_center)).to be_nil
    end
  end

  # The effective total is generated by the database, so the record has to be
  # stored and read back before it carries one.
  describe "the effective total budget" do
    def effective(record) = helper.fin_format_wsjrdp_cost_center_effective_total_budget(record)

    it "shows the generated total and explains where it comes from" do
      record = WsjrdpCostCenter.create!(number: "K901", name: "Testkostenstelle",
        budget_2025: -1000, budget_2026: -500)

      value = effective(record.reload)
      expect(value[:value]).to eq(money("-1.500,00"))
      expect(value[:help]).to include("Automatisch berechnet")
    end

    it "keeps the explanation for a cost center without any budget" do
      value = effective(cost_center)
      expect(value[:value]).to be_nil
      expect(value[:help]).to be_present
    end
  end

  # The fields the finance type rules already answer for; what the partial gets
  # is asserted through the lookup, not through a method of this module.
  describe "the fields the type rules answer for" do
    def value_of(attr, **attrs) = helper.fin_format_attr(cost_center(**attrs), attr, ctx)

    it "shows the manager's name as stored" do
      expect(value_of(:manager_name, manager_name: "Test Person").value).to eq("Test Person")
    end

    it "leaves the empty description of a fresh cost center blank" do
      expect(value_of(:description)).to be_blank_value
    end
  end
end
