# Settings relevant for the hitobito_wsjrdp_2027 wagon
# Overrides settings from the main application
application:
  languages:
    de: Deutsch

  version: '1.0.2 - UL preregistration'

email:
  sender: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <anmeldung@worldscoutjamboree.de>" %>
  reply_to: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <info@worldscoutjamboree.de>" %>
  mass_recipient: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <anmeldung@worldscoutjamboree.de>" %>

status:
  registered: Registriert # Jeder der sich initial eingelogged hat
  printed: Anmeldung gedruckt # Jeder der alle Pflichfelder ausgefüllt und auf drucken gedrück hat
  upload: Upload vollständig # Jeder der seine Pflichtdokumente hochgeladen hat
  in_review: Dokumente in Überprüfung durch CMT # Uploads auf Unterschriften
  reviewed: Dokumente vollständig überprüft # Jeder der Alle notwendigen dokumente unterschrieben hochgeladen hat
  confirmed: Bestätigt durch CMT # Jeder der bestätigt Teil einer Unit des Kontingentes ist
  deregistration_noted: Abmeldung Vermerkt # Personen die sich abmelden wollen, bei denen es noch Klärungsbedarf gibt
  deregistered: Abgemeldet # Alle die nicht mehr am Jamboree Teilnehmen wollen

addresses:
  imported_countries:
    - DE

countries:
  prioritized:
    - --
    - DE

phone_number:
  predefined_labels:
    - --
    - Festnetz
    - Mobil
    - Teilnehmende*r
    - Personensorgeberechtigte*r 1 (Mobil)
    - Personensorgeberechtigte*r 2 (Mobil)
    - Personensorgeberechtigte*r 1 (Festnetz)
    - Personensorgeberechtigte*r 2 (Festnetz)
    - Primärer Notfallkontakt
    - Sekundärer Notfallkontakt
    - Arbeit
    - Fax
    - Andere
  default_country: DE

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: development@worldscoutjamboree.de
