# Settings relevant for the hitobito_wsjrdp_2027 wagon
# Overrides settings from the main application
application:
  name: WSJ2027
  languages:
    de: Deutsch

email:
  sender: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <anmeldung@worldscoutjamboree.de>" %>
  reply_to: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <info@worldscoutjamboree.de>" %>
  mass_recipient: <%= "Deutsches Kontingent zum World Scout Jamboree 2027  <anmeldung@worldscoutjamboree.de>" %>

status:
  registered: Registriert # Jeder der sich initial eingelogged hat
  printed: Anmeldung gedruckt # Jeder der alle Pflichfelder ausgefüllt und auf drucken gedrück hat
  upload: Upload vollständig # Jeder der seine Pflichtdokumente hochgeladen hat
  in_review: Dokumente in Überprüfung durch CMT # Uploads auf Unterschriften
  reviewed: Dokumente vollständig überprüft # Jeder der Alle notwendigen dokumente unterschrieben hochgeladen hat
  confirmed: Bestätigt durch CMT # Jeder der bestätigt Teil einer Unit des Kontingentes ist
  deregistration_noted: Abmeldung Vermerkt # Personen die sich abmelden wollen, bei denen es noch Klärungsbedarf gibt
  deregistered: Abgemeldet # Alle die nicht mehr am Jamboree Teilnehmen wollen

diets:
  omnivorous: "Allesesser"
  vegetarian: "Vegetarisch"
  vegan: "Vegan"
  kosher: "Koscher"
  halal: "Halal"

addresses:
  imported_countries:
    - DE

countries:
  prioritized:
    - --
    - DE

phone_number:
  predefined_labels:
    - --
    - Festnetz
    - Mobil
    - Teilnehmende*r
    - Personensorgeberechtigte*r 1 (Mobil)
    - Personensorgeberechtigte*r 2 (Mobil)
    - Personensorgeberechtigte*r 1 (Festnetz)
    - Personensorgeberechtigte*r 2 (Festnetz)
    - Primärer Notfallkontakt
    - Sekundärer Notfallkontakt
    - Arbeit
    - Fax
    - Andere
  default_country: DE

sepa_status:
  ok: OK  # Automatischer Einzug, alles OK
  in_review: In Überprüfung  # Fehler aufgetreten, wird geprüft
  invalid_account: Zahlungs-Konto nicht mehr gültig  # Automatischer Einzug: Konto gibt es nicht mehr
  missing: Zahlung ausstehend  # Automatischer Einzug, fehlender Betrag, z.B. wg. Rücklastschrift
  individual_ok: Individueller Zahlungsplan (OK)  # Individueller Zahlungsplan, aktuell OK
  individual_missing: Individueller Zahlungsplan (Zahlung ausstehend)  # Individueller Zahlungsplan, zu wenig Geldeingang

shirt_size:
  - Größe auswählen
  - XXS
  - XS
  - S
  - M
  - L
  - XL
  - XXL
  - XXXL
  - XXXXL

uniform_size:
  - Größe auswählen
  - Klufthemd XS 35/36 
  - Klufthemd S 37/38 
  - Klufthemd M 39/40
  - Klufthemd L 41/42
  - Klufthemd XL 43/44
  - Klufthemd XXL 45/46
  - Klufthemd XXXL 47/48
  - Klufthemd S-Schlank 38S
  - Klufthemd M-Schlank 40S
  - Klufthemd L-Schlank 42S
  - Klufthemd XL-Schlank 44S
  - Kluftbluse 34
  - Kluftbluse 36
  - Kluftbluse 38
  - Kluftbluse 40
  - Kluftbluse 42
  - Kluftbluse 44
  - Kluftbluse 46
  - Kluftbluse 48

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: development@worldscoutjamboree.de
