name: Docker Build & Push

on:
  push:
    branches:
      - main
    tags: 
      - "v*"

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add commit hash to version string
        run: |
          short_sha=${GITHUB_SHA::7}
          sed -i -E "s/([0-9]+\.[0-9]+\.[0-9]+)/\1-$short_sha/" lib/hitobito_wsjrdp_2027/version.rb
          cat lib/hitobito_wsjrdp_2027/version.rb

      - name: Prepare Tags
        id: taggen
        run: |
          BASE="ghcr.io/${{ github.repository }}"
          APP_TAGS="$BASE/app:latest"
          WEB_TAGS="$BASE/web:latest"

          if [ "${{ github.ref_type }}" == "tag" ]; then
            APP_TAGS="$BASE/app:stable,$BASE/app:${{ github.ref_name }}"
            WEB_TAGS="$BASE/web:stable,$BASE/web:${{ github.ref_name }}"
          fi

          echo "APP_TAGS=$APP_TAGS" >> $GITHUB_OUTPUT
          echo "WEB_TAGS=$WEB_TAGS" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Rails
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.prod
          target: app
          push: true
          tags: ${{ steps.taggen.outputs.APP_TAGS }}

      - name: Build and push Nginx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.prod
          target: web
          push: true
          tags: ${{ steps.taggen.outputs.WEB_TAGS }}
